### ISSUE TITLE
Multiple Streams using AioQuic 

### ISSUE THREAD

**Issue by devkdas** [Froggo8311/Shard#1]
hai ,

It is not an issue.
one small quick query

@Froggo8311 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code .

Sorry for raising an issue to ask this query.

Looking forward for your reply

Thank you.

**Comment by NovaAndrom3da** [comment]
Hi @Karthikdasari0423,

I personally have not messed around a lot with the `aioquic` module, but perhaps this issue on it's GitHub page could help.
https://github.com/aiortc/aioquic/issues/169

**Comment by devkdas** [comment]
Hello @Froggo8311 

Thank you for replying back.

sure.
anyway there were multiple issues created by others in the aioquic repository regarding this issue.(https://github.com/aiortc/aioquic/issues?q=is%3Aissue+is%3Aopen+streams).

Thank you.
@Karthikdasari0423

**Comment by devkdas** [comment]
Hello @Froggo8311

Thank you for replying back.

sure.
anyway there were multiple issues created by others in the aioquic
repository regarding this issue.(
https://github.com/aiortc/aioquic/issues?q=is%3Aissue+is%3Aopen+streams).

Thank you.
@Karthikdasari0423
